name: multi-repos-without-jq

on:
  workflow_dispatch:
    inputs:
      repositories_json:
        description: 'JSON de repos: ["repo-frontend","repo-backend"]'
        required: true
        default: '["repo-frontend","repo-backend","repo-utils"]'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJSON(inputs.repositories_json) }}
    steps:
      - name: Imprimir repo
        run: echo "Compilando ${{ matrix.repo }}..."

      - name: Calcular versión (simulada)
        id: ver
        shell: bash
        run: |
          MAJOR=$((RANDOM % 3 + 1))
          MINOR=$((RANDOM % 10))
          PATCH=$((RANDOM % 100))
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Versión calculada para ${{ matrix.repo }}: $VERSION"

      - name: Guardar par repo,version
        shell: bash
        run: |
          echo "${{ matrix.repo }},${{ steps.ver.outputs.version }}" > "/tmp/${{ matrix.repo }}.csv"
          cat "/tmp/${{ matrix.repo }}.csv"

      # ⬆️ NOMBRE ÚNICO POR RAMA DE MATRIZ
      - name: Subir artifact por repo
        uses: actions/upload-artifact@v4
        with:
          name: versions-${{ matrix.repo }}
          path: /tmp/${{ matrix.repo }}.csv
          if-no-files-found: error
          retention-days: 3

  collect:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      versions_array: ${{ steps.pack.outputs.versions_array }}
      versions_map: ${{ steps.pack.outputs.versions_map }}
    steps:
      # ⬇️ BAJAR TODOS LOS artifacts QUE MATCHEEN EL PATRÓN
      - name: Descargar todos los artifacts de versiones
        uses: actions/download-artifact@v4
        with:
          pattern: versions-*
          merge-multiple: true
          path: versions/

      - name: Ver archivos recibidos
        shell: bash
        run: |
          ls -lah versions/
          echo
          for f in versions/*.csv; do echo "== $f =="; cat "$f"; done

      - name: Empaquetar en JSON (sin jq)
        id: pack
        shell: bash
        run: |
          set -euo pipefail
          arr="["
          first=1
          for f in versions/*.csv; do
            IFS=',' read -r repo ver < "$f"
            repo=${repo//\"/\\\"}; ver=${ver//\"/\\\"}
            item="{\"repo\":\"$repo\",\"version\":\"$ver\"}"
            if [ $first -eq 1 ]; then arr="$arr$item"; first=0; else arr="$arr,$item"; fi
          done
          arr="$arr]"
          echo "versions_array=$arr" >> "$GITHUB_OUTPUT"

          map="{"
          first=1
          for f in versions/*.csv; do
            IFS=',' read -r repo ver < "$f"
            repo=${repo//\"/\\\"}; ver=${ver//\"/\\\"}
            kv="\"$repo\":\"$ver\""
            if [ $first -eq 1 ]; then map="$map$kv"; first=0; else map="$map,$kv"; fi
          done
          map="$map}"
